export const metadata = {
    title: 'Abu hasan',
    author: '',
    headerTitle: 'Abu Hasan',
    description: 'abuhasan portfolio made by me',
    language: 'en-us',
    siteUrl: 'https://abu-hasan.vercel.app',
    siteRepo: '',
    // siteLogo: '/static/images/logo_purple.png',
    // image: '/static/images/logo_square_purple.png',
    socialBanner: '',
    email: 'dev.abuhasan@gmail.com',
    github: '',
    twitter: 'https://twitter.com/twitter',
    facebook: '',
    youtube: '',
    linkedin: '',
    locale: 'en-US',
    analytics: {
        plausibleDataDomain: '',
        simpleAnalytics: false,
        googleAnalyticsId: '',
    },
    comment: {
        provider: 'giscus',
        giscusConfig: {
            repo: process.env.NEXT_PUBLIC_GISCUS_REPO,
            repositoryId: process.env.NEXT_PUBLIC_GISCUS_REPOSITORY_ID,
            category: process.env.NEXT_PUBLIC_GISCUS_CATEGORY,
            categoryId: process.env.NEXT_PUBLIC_GISCUS_CATEGORY_ID,
            mapping: 'pathname',
            reactions: '1',
            metadata: '0',
            theme: 'light',
            darkTheme: 'transparent_dark',
            themeURL: '',
        },
        utterancesConfig: {
            repo: process.env.NEXT_PUBLIC_UTTERANCES_REPO,
            issueTerm: '',
            label: '',
            theme: '',
            darkTheme: '',
        },
        disqus: {
            shortname: process.env.NEXT_PUBLIC_DISQUS_SHORTNAME,
        },
    },
}
